/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analytics: typeof import('./components/stats/Analytics.vue')['default']
    AppBar: typeof import('./components/asides/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Approve: typeof import('./components/workflows/Approve.vue')['default']
    Approved: typeof import('./components/Nofitications/Approved.vue')['default']
    CarouselFeature: typeof import('./components/Features/CarouselFeature.vue')['default']
    Dashboard: typeof import('./components/dashboard/Dashboard.vue')['default']
    DialogCreateNew: typeof import('./components/dialogs/DialogCreateNew.vue')['default']
    DialogError: typeof import('./components/dialogs/DialogError.vue')['default']
    DialogInfo: typeof import('./components/dialogs/DialogInfo.vue')['default']
    DialogSuccess: typeof import('./components/dialogs/DialogSuccess.vue')['default']
    DialogUpdate: typeof import('./components/dialogs/DialogUpdate.vue')['default']
    Drawer: typeof import('./components/asides/Drawer.vue')['default']
    Feature: typeof import('./components/Features/Feature.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    History: typeof import('./components/workflows/History.vue')['default']
    LoadingProgressCircle: typeof import('./components/dialogs/LoadingProgressCircle.vue')['default']
    NewRequest: typeof import('./components/Nofitications/NewRequest.vue')['default']
    Profile: typeof import('./components/privews/Profile.vue')['default']
    RecentActivity: typeof import('./components/stats/RecentActivity.vue')['default']
    Roles: typeof import('./components/managements/Roles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./components/stats/setting.vue')['default']
    Stats: typeof import('./components/stats/Stats.vue')['default']
    Status: typeof import('./components/workflows/Status.vue')['default']
    Uploadfile: typeof import('./components/uploads/Uploadfile.vue')['default']
    UploadImage: typeof import('./components/uploads/UploadImage.vue')['default']
    User: typeof import('./components/stats/User.vue')['default']
    Users: typeof import('./components/managements/Users.vue')['default']
  }
}
