/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analysis: typeof import('./components/stats/Analysis.vue')['default']
    Analytics: typeof import('./components/stats/Analytics.vue')['default']
    AppBar: typeof import('./components/asides/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Dashboard: typeof import('./components/dashboard/Dashboard.vue')['default']
    Drawer: typeof import('./components/asides/Drawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RecentActivity: typeof import('./components/stats/RecentActivity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./components/stats/setting.vue')['default']
    Stats: typeof import('./components/stats/Stats.vue')['default']
    User: typeof import('./components/stats/User.vue')['default']
  }
}
